### PR TITLE
Cleaned up files

### PR DESCRIPTION
**Pull request by JestynA**
Co-authored-by: Candie Hill <can330330@yahoo.com>
Co-authored-by: Martin Ng <kamartinng@gmail.com>
Co-authored-by: Hoon Park <hoon.park97@gmail.com>
Co-authored-by: Steven Nguyen <sateeven@gmail.com>

### CODE REVIEW

**Review by hoonpvrk — APPROVED** [review]
Looking good!

**Review by can619 — APPROVED** [review]
reviewed and approved

**Review by Sateeven — APPROVED** [review]
Great job, looks clean!

**Review by kamartinng — APPROVED** [review]
Approved! Great work cleaning up files

**Pull request merged**
